
# 注册中心配置
eureka:
  instance:
      hostname: localhost
      port: 1000
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
server:
  port: 1002
spring:
  datasource:
    password: 2210
    username: root
    url: jdbc:mysql://localhost:3306/icloud-dev?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
#Redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-active: 500
        max-wait: 10000
        min-idle: 5
        max-idle: 10
    password:
swagger:
  enable: true
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/auth?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    username: root
#    password: 2210
#    driver-class-name: com.mysql.jdbc.Driver
