# 注册中心配置
eureka:
  instance:
      hostname: localhost
      port: 1000
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
server:
  port: 1002
spring:
  datasource:
    password: 2210
    username: root
    url: jdbc:mysql://10.28.254.216:3306/icloud-dev?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
#Redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-active: 500
        max-wait: 10000
        min-idle: 5
        max-idle: 10
    password:
swagger:
  enable: true

# 文件上传
oss-server:
  appid: oss216sg3
  appsecret: y878o83o
  endpoint: http://10.28.254.215:18000/
  application: test
